export const blogPosts = [
  {
    slug: 'marketing-automation-roi-2026',
    title: 'Marketing Automation ROI in 2026: Real Numbers, the Right Formulas, and Where the Math Gets Lied About',
    excerpt: 'Every vendor quotes Nucleus Research\'s $5.44 return figure — from 2014. Here are the real 2026 marketing automation ROI formulas, honest benchmarks, and a 90-day measurement framework that shows you where the math actually holds.',
    date: 'May 2026',
    dateIso: '2026-05-28',
    readTime: '10 min read',
    tags: ['Marketing Automation', 'ROI', 'B2B Growth'],
  },
  {
    slug: 'best-ai-automation-tools-2026',
    title: 'The Best AI Automation Tools in 2026 (Honest Comparison by Use Case)',
    excerpt: 'There is no single best AI automation tool — only the best one for your use case, volume, and team. A no-affiliate, operator comparison of Zapier, Make, n8n, Relevance AI, Gumloop, Lindy, Clay and more, grouped by job-to-be-done.',
    date: 'May 2026',
    dateIso: '2026-05-22',
    readTime: '11 min read',
    tags: ['AI Automation', 'Tools', 'Comparison'],
  },
  {
    slug: 'ai-automation-examples',
    title: '27 Real AI Automation Examples by Business Function (2026)',
    excerpt: 'The fastest way to find your own opportunity is to see what others automated. 27 concrete AI business automation examples across sales, marketing, support, operations, finance and HR — every one in production today.',
    date: 'May 2026',
    dateIso: '2026-05-22',
    readTime: '10 min read',
    tags: ['AI Automation', 'Examples', 'AI for Business'],
  },
  {
    slug: 'ai-automation-for-small-business',
    title: 'AI Automation for Small Business: Where to Start (and What to Skip) in 2026',
    excerpt: 'Small businesses have the most to gain from AI automation and the least margin for a failed experiment. Where to start, what to skip, what it costs, and how to do it without a technical team or a big budget.',
    date: 'May 2026',
    dateIso: '2026-05-21',
    readTime: '9 min read',
    tags: ['AI Automation', 'Small Business', 'Growth Systems'],
  },
  {
    slug: 'ai-lead-qualification',
    title: 'AI Lead Qualification: How to Score and Route Leads Automatically (2026)',
    excerpt: 'AI lead qualification scores and routes every inbound lead before a human touches it, so reps only work the leads worth working. How automated fit + intent scoring works, how to set it up, and where to keep a human.',
    date: 'May 2026',
    dateIso: '2026-05-21',
    readTime: '9 min read',
    tags: ['Lead Qualification', 'AI Automation', 'Sales Ops'],
  },
  {
    slug: 'ai-business-process-automation',
    title: 'AI Business Process Automation: A Practical Guide for B2B Teams (2026)',
    excerpt: 'Business process automation runs an end-to-end workflow with no manual hand-offs — and AI adds judgment to the steps that used to need a human. How to choose the right process, automate it without breaking it, and where AI belongs vs plain rules.',
    date: 'May 2026',
    dateIso: '2026-05-20',
    readTime: '10 min read',
    tags: ['AI Automation', 'Business Process', 'Operations'],
  },
  {
    slug: 'how-to-integrate-ai-into-your-business',
    title: 'How to Integrate AI Into Your Business: A Step-by-Step 2026 Playbook',
    excerpt: 'Integrating AI is a loop, not a launch: one workflow, ready data, smallest useful build, measured against a baseline, team trained, then expand. The order of operations that avoids doing nothing and doing everything at once.',
    date: 'May 2026',
    dateIso: '2026-05-20',
    readTime: '9 min read',
    tags: ['AI Integration', 'AI Automation', 'Strategy'],
  },
  {
    slug: 'what-is-an-ai-automation-agency',
    title: 'What Is an AI Automation Agency? What They Do, What It Costs, and How to Choose',
    excerpt: 'An AI automation agency builds custom systems that do work your team does by hand — and the good ones hand you an asset you own. What the category includes, 2026 pricing, and the red flags that separate a real agency from a reseller.',
    date: 'May 2026',
    dateIso: '2026-05-22',
    readTime: '9 min read',
    tags: ['AI Automation', 'Agency', 'B2B Growth'],
  },
  {
    slug: 'ai-automation-services-explained',
    title: "AI Automation Services Explained: What's Included, What's Hype, and What to Pay in 2026",
    excerpt: '"AI automation services" hides huge differences in value. The six service categories, where AI business automation actually pays off, where it is sold as magic, and what each pricing model should really cost.',
    date: 'May 2026',
    dateIso: '2026-05-22',
    readTime: '9 min read',
    tags: ['AI Automation', 'Services', 'Growth Systems'],
  },
  {
    slug: 'llm-agents-for-business',
    title: 'LLM Agents for Business: How They Automate Real Work in 2026 (Without the Hype)',
    excerpt: 'An LLM agent is a model wrapped in a reason-act-observe loop that can use tools and take real steps. Where LLM automation works today, where it still breaks, how it is built, and whether your business should use it yet.',
    date: 'May 2026',
    dateIso: '2026-05-22',
    readTime: '10 min read',
    tags: ['LLM Agents', 'AI Automation', 'AI Systems'],
  },
  {
    slug: 'do-you-need-an-ai-automation-consultant',
    title: 'Do You Need an AI Automation Consultant? When to Hire One vs Build In-House',
    excerpt: 'A consultant is worth real money in one situation: when you do not yet know what to automate or in what order. How to tell whether your real problem is strategy or execution — and avoid paying for a deck you never act on.',
    date: 'May 2026',
    dateIso: '2026-05-21',
    readTime: '8 min read',
    tags: ['AI Automation', 'Consulting', 'Strategy'],
  },
  {
    slug: 'generative-ai-for-business-use-cases',
    title: 'Generative AI for Business: 12 Use Cases That Actually Move Revenue (2026)',
    excerpt: 'Most generative AI lists are 40 ideas, 35 of them demos. Here are 12 use cases that pay for themselves — grouped by whether they make money, save time, or reduce risk — plus where generative AI still loses money.',
    date: 'May 2026',
    dateIso: '2026-05-21',
    readTime: '10 min read',
    tags: ['Generative AI', 'AI for Business', 'AI Systems'],
  },
  {
    slug: 'cold-email-personalization-at-scale',
    title: 'Personalization at Scale Without Sounding Like a Bot: The AI + Spintax Division of Labor',
    excerpt: 'Fully AI-generated personalization reads generic and prospects can smell it. Here’s the division of labor — spintax for structure, AI for the one line that matters, humans for the angle — that keeps reply rates high at volume.',
    date: 'May 2026',
    dateIso: '2026-05-20',
    readTime: '9 min read',
    tags: ['Personalization', 'AI Copy', 'Cold Email'],
  },
  {
    slug: 'build-in-house-or-hire-cold-email-agency',
    title: 'Build It In-House or Hire an Agency? A B2B Outbound Decision Framework',
    excerpt: 'The true cost of DIY cold email isn’t the tools — it’s the ramp time and the domains you’ll burn learning. A decision framework for building in-house, hiring an agency, or running the hybrid model.',
    date: 'May 2026',
    dateIso: '2026-05-20',
    readTime: '9 min read',
    tags: ['Agency vs DIY', 'Cold Email', 'B2B Growth'],
  },
  {
    slug: 'cold-email-for-recruiting-agencies',
    title: "Cold Email for Recruiting Agencies: What's Different (2026 Playbook)",
    excerpt: 'Recruiting is a two-sided market — you’re selling to clients and sourcing candidates at once. The ICP signals, copy angles, and compliance rules that make cold email work for recruiting agencies specifically.',
    date: 'May 2026',
    dateIso: '2026-05-20',
    readTime: '8 min read',
    tags: ['Vertical', 'Recruiting', 'Cold Email'],
  },
  {
    slug: 'sales-automation-roi-calculator',
    title: 'The Real ROI of Sales Automation: How to Calculate Hours and Dollars Before You Spend',
    excerpt: 'Before you buy automation, run the math. The three ROI equations (time, cost, revenue), realistic 2026 benchmarks, a worked example, and an honest look at where automation ROI gets overstated.',
    date: 'May 2026',
    dateIso: '2026-05-19',
    readTime: '9 min read',
    tags: ['ROI', 'Sales Automation', 'Growth Systems'],
  },
  {
    slug: 'b2b-cold-email-benchmarks-2026',
    title: 'Realistic B2B Cold Email Benchmarks in 2026: Reply Rates, Meetings & Why Small Sends Win',
    excerpt: 'Vendor benchmark reports inflate every number. Here are the realistic 2026 figures — reply rates, positive replies, meetings per hundred sends — and why small, targeted sends beat big blasts.',
    date: 'May 2026',
    dateIso: '2026-05-19',
    readTime: '9 min read',
    tags: ['Benchmarks', 'Cold Email', 'Data'],
  },
  {
    slug: 'is-cold-email-still-worth-it-2026',
    title: "Is Cold Email Still Worth It in 2026? An Honest Operator's Answer",
    excerpt: 'Yes — but only under specific conditions. Where cold email still beats paid ads 3-8x on cost per opportunity, where it quietly fails, and an honest list of when it’s simply not right for your business.',
    date: 'May 2026',
    dateIso: '2026-05-18',
    readTime: '8 min read',
    tags: ['Strategy', 'Cold Email', 'B2B Growth'],
  },
  {
    slug: 'n8n-vs-make-vs-zapier-sales-automation',
    title: 'n8n vs Make vs Zapier for Sales Automation: Which to Use at Your Volume',
    excerpt: 'Per-task, per-operation, or per-execution billing changes everything at scale. A volume-first comparison of n8n, Make, and Zapier for lead routing, enrichment, and follow-up automation.',
    date: 'May 2026',
    dateIso: '2026-05-17',
    readTime: '10 min read',
    tags: ['Automation', 'n8n', 'Sales Ops'],
  },
  {
    slug: 'cold-email-vs-linkedin-outreach-2026',
    title: 'Cold Email vs LinkedIn Outreach in 2026: Why the Winners Run Both',
    excerpt: 'Email scales, LinkedIn warms. The realistic reply rates for each, the limits and ban risk of LinkedIn, and an exact day-by-day multichannel cadence that lifts reply rates above either channel alone.',
    date: 'May 2026',
    dateIso: '2026-05-16',
    readTime: '9 min read',
    tags: ['Multichannel', 'Cold Email', 'LinkedIn'],
  },
  {
    slug: 'cold-email-gmail-promotions-tab-fix',
    title: "Why Your Cold Email Lands in Gmail's Promotions Tab (and the Plain-Text Fix)",
    excerpt: 'Promotions isn’t spam — but it’s where outreach goes to die. The signals that trigger Gmail’s tab classifier (including the counterintuitive List-Unsubscribe header), and the plain-text fix that gets you to Primary.',
    date: 'May 2026',
    dateIso: '2026-05-15',
    readTime: '8 min read',
    tags: ['Deliverability', 'Cold Email', 'Gmail'],
  },
  {
    slug: 'cold-email-infrastructure-how-many-domains-inboxes',
    title: 'Cold Email Infrastructure in 2026: Exactly How Many Domains and Inboxes You Need',
    excerpt: 'The tactical math, not vague advice: 3 inboxes per domain, 30-40 sends per inbox per day, the warm-up timeline, the Feb-2024 bulk-sender rules, and how to size your infrastructure for a target monthly volume.',
    date: 'May 2026',
    dateIso: '2026-05-14',
    readTime: '10 min read',
    tags: ['Infrastructure', 'Cold Email', 'Email Infrastructure'],
  },
  {
    slug: 'how-to-vet-a-cold-email-agency-red-flags',
    title: 'How to Vet a Cold Email Agency: 9 Red Flags That Predict a Failed Engagement',
    excerpt: 'Most agency horror stories were predictable on the sales call. Nine red flags — from main-domain sending to vanity metrics to who keeps the infrastructure — and the exact questions to ask before you sign.',
    date: 'May 2026',
    dateIso: '2026-05-13',
    readTime: '8 min read',
    tags: ['Agency Vetting', 'Cold Email', 'B2B Growth'],
  },
  {
    slug: 'cold-email-agency-cost-2026',
    title: 'What a B2B Cold Email Agency Actually Costs in 2026 (And What You Get at Each Tier)',
    excerpt: 'Transparent pricing: the three real tiers ($2.5k–$15k+/mo), cost per meeting, how that compares to a loaded in-house SDR, and the pricing red flags that signal you’ll overpay for underperformance.',
    date: 'May 2026',
    dateIso: '2026-05-12',
    readTime: '9 min read',
    tags: ['Pricing', 'Agency vs In-House', 'B2B Growth'],
  },
  {
    slug: 'ai-sales-agents-2026-what-works',
    title: "AI Sales Agents in 2026: What Actually Works (and What's Just Demos)",
    excerpt: "Every SaaS founder asks if they can replace SDRs with AI agents yet. Here's an honest 2026 read on what reliably works, what still breaks, how to evaluate the new wave of 'AI SDR' products before buying, and a full tool comparison of 11x, AiSDR, Artisan, and custom stacks.",
    date: 'May 2026',
    dateIso: '2026-05-28',
    readTime: '10 min read',
    tags: ['AI Agents', 'Sales Automation', 'AI Systems'],
  },
  {
    slug: 'b2b-lead-qualification-bant-meddic-champ-2026',
    title: 'B2B Lead Qualification in 2026: BANT vs MEDDIC vs CHAMP (and What Actually Works)',
    excerpt: 'Most qualification frameworks are sales-coach theater. A decision matrix for BANT, MEDDIC, MEDDPICC, CHAMP, GPCT, ANUM, and FAINT — plus a leaner four-question framework that works across deal sizes.',
    date: 'May 2026',
    dateIso: '2026-05-08',
    readTime: '9 min read',
    tags: ['Sales', 'Qualification', 'Sales Process'],
  },
  {
    slug: 'cold-email-deliverability-spf-dkim-dmarc-guide',
    title: 'Cold Email Deliverability: SPF, DKIM, DMARC & Sender Reputation (B2B Guide)',
    excerpt: 'If your email lands in spam, copy doesn’t matter. The full deliverability stack: SPF/DKIM/DMARC setup, dedicated cold-email domains, warm-up timeline, sending volume, reputation killers, and blocklist recovery.',
    date: 'April 2026',
    dateIso: '2026-04-30',
    readTime: '10 min read',
    tags: ['Cold Email', 'Deliverability', 'Email Infrastructure'],
  },
  {
    slug: 'cold-email-subject-lines-that-get-b2b-replies',
    title: 'Cold Email Subject Lines That Actually Get B2B Replies (2026 Playbook)',
    excerpt: 'Most cold emails die at the subject line. Six subject-line archetypes that work in B2B, eight patterns that kill reply rate, and the A/B testing rules that produce statistically real winners.',
    date: 'April 2026',
    dateIso: '2026-04-30',
    readTime: '9 min read',
    tags: ['Cold Email', 'Subject Lines', 'Conversion'],
  },
  {
    slug: 'how-to-find-verified-emails-b2b-cold-outreach',
    title: 'How To Find Verified Emails for B2B Cold Outreach (Without Buying Lists)',
    excerpt: 'Bought lists tank your deliverability and your reputation. A 3-layer source/enrichment/verification stack that produces clean, fresh B2B emails at >95% deliverability, plus GDPR/CAN-SPAM ground rules.',
    date: 'April 2026',
    dateIso: '2026-04-30',
    readTime: '8 min read',
    tags: ['Lead Gen', 'Prospecting', 'Email Verification'],
  },
  {
    slug: 'how-to-know-if-your-business-needs-ai-automation',
    title: 'How To Know If Your Business Is Ready For AI Automation',
    excerpt: "Not every business needs AI automation right now. A 5-question framework to find out if you're ready, what to build first, and how to calculate ROI before spending a dollar.",
    date: 'April 2026',
    dateIso: '2026-04-29',
    readTime: '6 min read',
    tags: ['AI Automation', 'ROI', 'Growth Systems'],
  },
  {
    slug: 'crm-automation-systems-for-b2b',
    title: 'CRM Automation: How Stage-Based Triggers Free Up Your Sales Team',
    excerpt: "Move a lead from one CRM stage to another and the right email fires automatically. Here's how stage-based automation gives each rep 9-14 hours back every week.",
    date: 'April 2026',
    dateIso: '2026-04-29',
    readTime: '7 min read',
    tags: ['CRM', 'Sales Automation', 'Sales Ops'],
  },
  {
    slug: 'follow-up-system-for-b2b',
    title: "You Don't Have a Lead Problem. You Have a Follow-Up Problem.",
    excerpt: "Most B2B companies have enough leads — they just stop following up after 2-3 touches. Here's how an automated follow-up system recovers that revenue, with ROI from day one.",
    date: 'April 2026',
    dateIso: '2026-04-29',
    readTime: '7 min read',
    tags: ['Follow-Up', 'Conversion', 'Revenue Recovery'],
  },
  {
    slug: 'ai-lead-generation-for-b2b-companies',
    title: 'AI Lead Generation for B2B Companies: A 2026 Playbook',
    excerpt: 'The 2026 guide to AI lead generation for B2B: which AI does what, where humans still win, realistic conversion benchmarks, and the exact stack we deploy.',
    date: 'April 2026',
    dateIso: '2026-04-28',
    readTime: '9 min read',
    tags: ['AI Lead Gen', 'B2B Sales', 'Sales Automation'],
  },
  {
    slug: 'cold-email-vs-paid-ads-b2b',
    title: 'Cold Email vs Paid Ads: Which Actually Works for B2B in 2026?',
    excerpt: 'Capped cost vs uncapped bidding, B2B-only reach, and why ICP fit decides the channel before strategy does. A founder-level breakdown.',
    date: 'April 2026',
    dateIso: '2026-04-25',
    readTime: '8 min read',
    tags: ['Cold Email', 'Paid Ads', 'B2B Marketing'],
  },
  {
    slug: 'ai-vs-human-cold-email-copy',
    title: 'AI vs Human Cold Email Copy: Why Full Automation Kills Your Reply Rate',
    excerpt: "Fully AI-generated cold email copy looks personalized but reads like a template — and prospects can tell. Here's the hybrid that actually books meetings.",
    date: 'April 2026',
    dateIso: '2026-04-22',
    readTime: '7 min read',
    tags: ['Cold Email', 'AI Copy', 'Personalization'],
  },
  {
    slug: 'why-you-should-own-your-cold-email-infrastructure',
    title: 'Why You Should Own Your Cold Email Infrastructure (Not Rent It From An Agency)',
    excerpt: "Most B2B agencies walk off with your leads when you stop paying. Here's why owning the infrastructure — domains, mailboxes, CRM — is the only sustainable path.",
    date: 'April 2026',
    dateIso: '2026-04-15',
    readTime: '6 min read',
    tags: ['Cold Email', 'Agency vs In-House', 'B2B Growth'],
  },
  {
    slug: 'cold-email-system-20-appointments-month',
    title: 'How We Get 15-20 Qualified Appointments Per Month With Cold Email',
    excerpt: "The average business relies on referrals and struggles to get 2-3 meetings a month. Here's the exact system we deploy at a realistic 4% reply rate.",
    date: 'March 2026',
    dateIso: '2026-03-06',
    readTime: '8 min read',
    tags: ['Cold Email', 'Lead Gen', 'AI Systems'],
  },
];

export function getRelatedPosts(currentSlug, count = 3) {
  return blogPosts.filter((p) => p.slug !== currentSlug).slice(0, count);
}
