export const blogPosts = [
  {
    slug: 'ai-sales-agents-2026-what-works',
    title: "AI Sales Agents in 2026: What Actually Works (and What's Just Demos)",
    excerpt: "Every SaaS founder asks if they can replace SDRs with AI agents yet. Here's an honest 2026 read on what reliably works, what still breaks, and how to evaluate the new wave of 'AI SDR' products before buying.",
    date: 'May 2026',
    dateIso: '2026-05-10',
    readTime: '10 min read',
    tags: ['AI Agents', 'Sales Automation', 'AI Systems'],
  },
  {
    slug: 'b2b-lead-qualification-bant-meddic-champ-2026',
    title: 'B2B Lead Qualification in 2026: BANT vs MEDDIC vs CHAMP (and What Actually Works)',
    excerpt: 'Most qualification frameworks are sales-coach theater. A decision matrix for BANT, MEDDIC, MEDDPICC, CHAMP, GPCT, ANUM, and FAINT — plus a leaner four-question framework that works across deal sizes.',
    date: 'May 2026',
    dateIso: '2026-05-08',
    readTime: '9 min read',
    tags: ['Sales', 'Qualification', 'Sales Process'],
  },
  {
    slug: 'cold-email-deliverability-spf-dkim-dmarc-guide',
    title: 'Cold Email Deliverability: SPF, DKIM, DMARC & Sender Reputation (B2B Guide)',
    excerpt: 'If your email lands in spam, copy doesn’t matter. The full deliverability stack: SPF/DKIM/DMARC setup, dedicated cold-email domains, warm-up timeline, sending volume, reputation killers, and blocklist recovery.',
    date: 'April 2026',
    dateIso: '2026-04-30',
    readTime: '10 min read',
    tags: ['Cold Email', 'Deliverability', 'Email Infrastructure'],
  },
  {
    slug: 'cold-email-subject-lines-that-get-b2b-replies',
    title: 'Cold Email Subject Lines That Actually Get B2B Replies (2026 Playbook)',
    excerpt: 'Most cold emails die at the subject line. Six subject-line archetypes that work in B2B, eight patterns that kill reply rate, and the A/B testing rules that produce statistically real winners.',
    date: 'April 2026',
    dateIso: '2026-04-30',
    readTime: '9 min read',
    tags: ['Cold Email', 'Subject Lines', 'Conversion'],
  },
  {
    slug: 'how-to-find-verified-emails-b2b-cold-outreach',
    title: 'How To Find Verified Emails for B2B Cold Outreach (Without Buying Lists)',
    excerpt: 'Bought lists tank your deliverability and your reputation. A 3-layer source/enrichment/verification stack that produces clean, fresh B2B emails at >95% deliverability, plus GDPR/CAN-SPAM ground rules.',
    date: 'April 2026',
    dateIso: '2026-04-30',
    readTime: '8 min read',
    tags: ['Lead Gen', 'Prospecting', 'Email Verification'],
  },
  {
    slug: 'how-to-know-if-your-business-needs-ai-automation',
    title: 'How To Know If Your Business Is Ready For AI Automation',
    excerpt: "Not every business needs AI automation right now. A 5-question framework to find out if you're ready, what to build first, and how to calculate ROI before spending a dollar.",
    date: 'April 2026',
    dateIso: '2026-04-29',
    readTime: '6 min read',
    tags: ['AI Automation', 'ROI', 'Growth Systems'],
  },
  {
    slug: 'crm-automation-systems-for-b2b',
    title: 'CRM Automation: How Stage-Based Triggers Free Up Your Sales Team',
    excerpt: "Move a lead from one CRM stage to another and the right email fires automatically. Here's how stage-based automation gives each rep 9-14 hours back every week.",
    date: 'April 2026',
    dateIso: '2026-04-29',
    readTime: '7 min read',
    tags: ['CRM', 'Sales Automation', 'Sales Ops'],
  },
  {
    slug: 'follow-up-system-for-b2b',
    title: "You Don't Have a Lead Problem. You Have a Follow-Up Problem.",
    excerpt: "Most B2B companies have enough leads — they just stop following up after 2-3 touches. Here's how an automated follow-up system recovers that revenue, with ROI from day one.",
    date: 'April 2026',
    dateIso: '2026-04-29',
    readTime: '7 min read',
    tags: ['Follow-Up', 'Conversion', 'Revenue Recovery'],
  },
  {
    slug: 'ai-lead-generation-for-b2b-companies',
    title: 'AI Lead Generation for B2B Companies: A 2026 Playbook',
    excerpt: 'The 2026 guide to AI lead generation for B2B: which AI does what, where humans still win, realistic conversion benchmarks, and the exact stack we deploy.',
    date: 'April 2026',
    dateIso: '2026-04-28',
    readTime: '9 min read',
    tags: ['AI Lead Gen', 'B2B Sales', 'Sales Automation'],
  },
  {
    slug: 'cold-email-vs-paid-ads-b2b',
    title: 'Cold Email vs Paid Ads: Which Actually Works for B2B in 2026?',
    excerpt: 'Capped cost vs uncapped bidding, B2B-only reach, and why ICP fit decides the channel before strategy does. A founder-level breakdown.',
    date: 'April 2026',
    dateIso: '2026-04-25',
    readTime: '8 min read',
    tags: ['Cold Email', 'Paid Ads', 'B2B Marketing'],
  },
  {
    slug: 'ai-vs-human-cold-email-copy',
    title: 'AI vs Human Cold Email Copy: Why Full Automation Kills Your Reply Rate',
    excerpt: "Fully AI-generated cold email copy looks personalized but reads like a template — and prospects can tell. Here's the hybrid that actually books meetings.",
    date: 'April 2026',
    dateIso: '2026-04-22',
    readTime: '7 min read',
    tags: ['Cold Email', 'AI Copy', 'Personalization'],
  },
  {
    slug: 'why-you-should-own-your-cold-email-infrastructure',
    title: 'Why You Should Own Your Cold Email Infrastructure (Not Rent It From An Agency)',
    excerpt: "Most B2B agencies walk off with your leads when you stop paying. Here's why owning the infrastructure — domains, mailboxes, CRM — is the only sustainable path.",
    date: 'April 2026',
    dateIso: '2026-04-15',
    readTime: '6 min read',
    tags: ['Cold Email', 'Agency vs In-House', 'B2B Growth'],
  },
  {
    slug: 'cold-email-system-20-appointments-month',
    title: 'How We Get 15-20 Qualified Appointments Per Month With Cold Email',
    excerpt: "The average business relies on referrals and struggles to get 2-3 meetings a month. Here's the exact system we deploy at a realistic 4% reply rate.",
    date: 'March 2026',
    dateIso: '2026-03-06',
    readTime: '8 min read',
    tags: ['Cold Email', 'Lead Gen', 'AI Systems'],
  },
];

export function getRelatedPosts(currentSlug, count = 3) {
  return blogPosts.filter((p) => p.slug !== currentSlug).slice(0, count);
}
